### ISSUE TITLE
F9_Clones_Select_Storage - Observación 1

### ISSUE THREAD

**Issue by sofilibi** [omarbenites/DC-Mama-Bebe#2]
Estimado Omar:
Por favor revisar  la hoja "F9_Clones_Select_Storage", el poblema es que no se está calculado bien el "SGLOB" y aparece en una columna aparte el que debería ser el resulado.
Gracias.

SCMEN	SCWM	SGLOB	PMEN	PWM	PGLOB				
4	1	4	11.43	2.33	11.43				5
8	8	8	22.86	18.6	22.86				16

**Comment by omarbenites** [comment]
Corregido! dispoinble en nueva version 7/30/2015 en la web

**Comment by sofilibi** [comment]
Muchas Gracias! x 3 :)
