### ISSUE TITLE
Summary by clone

### ISSUE THREAD

**Issue by sofilibi** [omarbenites/DC-Mama-Bebe#4]
En Summary by clone en uno de los libros se generaron 2 clones mas que no esan en la lista de materiales, solo existe el clon "CIP396311.1", pero se generaron esos otros
CIP396311.2,
CIP396311.3.
y luego se genera una linea en blanco con valores.
.

**Comment by omarbenites** [comment]
Soft, Estuve chequeando ese fieldbook  PTPV201111_DEBIGONJ , y si aparecen en el
F5_harvest_Baby :

![image](https://cloud.githubusercontent.com/assets/5264796/8806516/a2927502-2f9c-11e5-80d0-ddeeee0a9da0.png)

Lo de la linea en blanco, ya lo estoy corrigiendo.

Saludos y gracias por estar usando este servicio :dancer:

**Comment by sofilibi** [comment]
Es cierto!! ya los vii! no me habia dado cuenta, ya que no estan en otro lado! muchas graciass!!!....
