### ISSUE TITLE
ANOVA

### ISSUE THREAD

**Issue by sofilibi** [omarbenites/DC-Mama-Bebe#5]
Este es solo un pequeño detalle
dice "Tratamiento" en vez de "treatment"

True treatment averages 
------------------------------------ 
     Tratamiento

**Comment by omarbenites** [comment]
Hola, disculpa en que Sheet sale eso?

**Comment by sofilibi** [comment]
En  las hojas que se generan en el ANOVA, las que hacen los resumenes y x ejemplo hace la prueba de Shapiro-wild...?? en esas hojas...en las tablitas
